const HEALTH_CHECK_INTERVAL_MINUTES = 1;
const HEALTH_CHECK_CRON_SCHEDULE = `*/${HEALTH_CHECK_INTERVAL_MINUTES} * * * *`;
const HEALTH_CHECK_BATCH_SIZE = 10;
const HEALTH_CHECK_REQUEST_TIMEOUT_MS = 10000;
const HISTORY_DEFAULT_PAGE = 1;
const HISTORY_DEFAULT_LIMIT = 20;
const HISTORY_MAX_LIMIT = 100;

module.exports = {
  HEALTH_CHECK_INTERVAL_MINUTES,
  HEALTH_CHECK_CRON_SCHEDULE,
  HEALTH_CHECK_BATCH_SIZE,
  HEALTH_CHECK_REQUEST_TIMEOUT_MS,
  HISTORY_DEFAULT_PAGE,
  HISTORY_DEFAULT_LIMIT,
  HISTORY_MAX_LIMIT,
};
